### ISSUE TITLE
SQL注入误报

### ISSUE THREAD

**Issue by york-cmd** [chushuai/wscan#10]
当页面被waf拦截时,页面为403会检测出boolean注入  而且全站所有参数都报注入点
<img width="1370" alt="image" src="https://github.com/chushuai/wscan/assets/64241747/49f63971-cd40-4943-be66-ea34ce31421e">

**Comment by chushuai** [comment]
最新版已修复, 麻烦验证一下 @york-cmd 
https://github.com/chushuai/wscan/releases

**Comment by york-cmd** [comment]
大佬 该问题已修复

另外是否可以优化一下  如果没有漏洞的情况下不输出报告呢?
