### ISSUE TITLE
反连为何跑不起来

### ISSUE THREAD

**Issue by HiIk-9527** [chushuai/wscan#11]
![image](https://github.com/chushuai/wscan/assets/69377487/156f10c5-a6ec-43b0-84d7-65a341be628b)

**Comment by HiIK-666** [comment]
刚执行就退出了

**Comment by chushuai** [comment]
我这边测试没有问题，参考配置
![image](https://github.com/chushuai/wscan/assets/5875458/c8921fd8-f2d5-41b8-9dae-16123f45a58e)
![image](https://github.com/chushuai/wscan/assets/5875458/b90cad21-1506-410a-992c-5eeb1bb0a09f)

**Comment by HiIK-666** [comment]
使用最新跑起来了

**Comment by chushuai** [comment]
新版的返连平台已经发布 @HiIK-666  
![image](https://github.com/chushuai/wscan/assets/5875458/e6808b17-d725-48fe-8c76-3cc29affac85)

**Comment by HiIk-9527** [comment]
http server is not enabled
![image](https://github.com/chushuai/wscan/assets/69377487/71036932-d303-4fc8-a0f4-4ce82ac647fc)

http已经开启了
![image](https://github.com/chushuai/wscan/assets/69377487/df2adc5d-3ace-4e2f-93a0-6e5c8a598f73)
访问页面貌似有点bug,并不需要进行登录,就能直接查看和操作

**Comment by HiIk-9527** [comment]
客户端配置
    client:
        remote_server: true
        http_base_url: "http://1.1.1.1:1111"
        dns_server_ip: "1.1.1.1"
