### ISSUE TITLE
疑问和建议

### ISSUE THREAD

**Issue by guguyu1** [chushuai/wscan#12]
一，建议
针对参数fuzz 个人觉得需要尽快支持反连或者dnslog 因为log4j漏洞还是有一定存量的，而且fuzz本身就是模糊测试，以往的fuzz出来的漏洞均需配合dnslog

二，针对参数fuzz 或者现有的功能，如sql注入xss等 对参数的解析是怎么样的
 如
POST /sys/customer/list HTTP/1.1
Host: www.baidu.com
Content-Length: 23
Content-Type: application/json;charset=UTF-8

{"key1":"value1","key2":"eyJpbm5lcmtleTEiOiJpbm5lcnZhbHVlMSJ9","id":1,"isLogin":false,"key3":{"innerkey2":"{\"k3\":\"v3\"}"}}
污染 key1 的值然后分别发包

污染 key2 的值然后分别发包

尝试自动解码 key2 ，并污染子 JSON 的 innerkey1 的值然后分别发包

污染 key3 的值然后分别发包。

污染 key3 的子 JSON 的 innerkey2 的值，然后分别发包。

尝试解析 innerkey2 ，并污染子JSON的 k3 的值然后分别发包

理论上总的请求量是 3*6=18 次

或者 a=123&b={"innerkey2":"{\"k3\":\"v3\"}"}
{"key1":"value1","key2":["aa","bb"]

发包量较大的话，是否还需要增加参数便利深度配置

很感谢师傅能开源这么棒的项目，向你们致敬！

**Comment by guguyu1** [comment]
哦对  附上一个参考链接，https://mp.weixin.qq.com/s/NYGBUWY820TDfnaHldxuow

**Comment by chushuai** [comment]
@guguyu1 已经支持返连平台了，参考说明文档

**Comment by guguyu1** [comment]
自定义fuzz参数模板好像没有返连机制

**Comment by chushuai** [comment]
name: custom-reverse

set:
  reverse: newReverse()
  reverseURL: reverse.url

payload:
  - wget {{reverseURL}}

placeholder:
  - query
  - body
  - header
  - cookie

expression: response.status == 200 && reverse.wait(15)

detail:
  author: shaochuyu
  links:
    - https://github.com/chushuai/wscan
  version: 1.0
