### ISSUE TITLE
xss扫描规则

### ISSUE THREAD

**Issue by yinhui1150** [chushuai/wscan#17]
请问下，是不是爬虫爬取到的所有URL都会扫描xss插件，如果不是，是根据什么标准来判断要跑xss插件的呢，在框架代码中没有看到这部分的逻辑

**Comment by chushuai** [comment]
XSS只会扫描响应类型为text/html的请求，对于那些与参数名相同的URL，会进行去重扫描。

**Comment by yinhui1150** [comment]
> XSS只会扫描响应类型为text/html的请求，对于那些与参数名相同的URL，会进行去重扫描。

您好，再继续问一下哈，除了根据content-type进行xss插件的判断，是否还有其他条件，如get请求带有参数或者post请求？如果页面存在注入点，wscan会扫描那些类型的的漏洞插件？整体的插件扫描匹配规则是怎样的呢？

**Comment by chushuai** [comment]
举个列子呢

**Comment by yinhui1150** [comment]
> 举个列子呢

如pikachu这个常见的靶机，在http://10.227.34.203/pikachu/vul/sqli/sqli_widebyte.php是个post请求，提交的表单数据是name=auro&submit=%E6%9F%A5%E8%AF%A2，在wscan这个框架中，他会扫描那些插件呢？另外一个url如http://10.227.34.203/pikachu/vul/sqli/sqli_str.php?name=111&submit=%E6%9F%A5%E8%AF%A2，这个url会扫描那些插件呢？

扫描sql注入插件或者xss插件是根据参数或者是post请求来判断的吗？

**Comment by chushuai** [comment]
不同的插件扫描目标是不一样的
有些每个站点只扫描一次
有些是针对目录，如
![image](https://github.com/chushuai/wscan/assets/5875458/f2d56fd5-828e-45e1-b9d3-fe6ef658d29e)

有些是针对所有请求，如
![image](https://github.com/chushuai/wscan/assets/5875458/f8e80be2-31f0-4688-913b-732ded7f7b71)

**Comment by yinhui1150** [comment]
> 不同的插件扫描目标是不一样的 有些每个站点只扫描一次 有些是针对目录，如 ![image](https://private-user-images.githubusercontent.com/5875458/346257863-f2d56fd5-828e-45e1-b9d3-fe6ef658d29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTA1NDksIm5iZiI6MTcyMDQ5MDI0OSwicGF0aCI6Ii81ODc1NDU4LzM0NjI1Nzg2My1mMmQ1NmZkNS04MjhlLTQ1ZTEtYjlkMy1mZTZlZjY1OGQyOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDE1NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ExMTE1MzkwNWM4MWI4ZWI0ZmU4YmEyNjBhM2M1ZGE0MWNmMmFmOTAxZmY2ZjM1N2M2Y2E0Zjc0YTlmZjA2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u1N99jrhTI9oTmmJKS7Q1zDkAoH8o2Z7Tov2koOYrlg)
> 
> 有些是针对所有请求，如 ![image](https://private-user-images.githubusercontent.com/5875458/346257800-f8e80be2-31f0-4688-913b-732ded7f7b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTA1NDksIm5iZiI6MTcyMDQ5MDI0OSwicGF0aCI6Ii81ODc1NDU4LzM0NjI1NzgwMC1mOGU4MGJlMi0zMWYwLTQ2ODgtOTEzYi03MzJkZWQ3ZjdiNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDE1NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE1MzZiZTBmZDU4NTU4M2JkYTNlMjdjYzNjZTkwYjExZmE1YTg1NjhjMmQzNGMyNGQ5YWQ0NTkyOGFlYzVhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xjFhLUAZlJKk7aMkHGR9nApjfMCQkyry6SGxiIrQiq0)

我看了wscan的代码，里面有一个placeholder的参数，此参数的含义好像是表明了什么样的URL会调用此插件，在对应漏洞的yml文件中，如path-traversal.yml中
![image](https://github.com/chushuai/wscan/assets/21555925/92729077-cfd9-4635-95d3-86176f3d7b41)
，按照此参数的理解，要想调用路径遍历的漏洞，当HTTP的请求是以/目录结尾的，或者存在URL参数，或者请求是表达，文件上传类的请求也会调用此插件，这样理解对吗？

**Comment by chushuai** [comment]
自定义的web通用漏洞扫描插件，适用于所有路径
