### ISSUE TITLE
bug: 指定config文件了，还是会自动生成config.yaml 文件

### ISSUE THREAD

**Issue by sudazzk** [chushuai/wscan#21]
./wscan_darwin_arm64 --config ./tm/config.yaml ws --basic-crawler http://testphp.vulnweb.com/
已经指定config，还是会在运行目录生成一个新的yaml文件

**Comment by chushuai** [comment]
感谢反馈，这周日新的版本会统一修复

**Comment by chushuai** [comment]
已经修复，下载最新版即可
https://github.com/chushuai/wscan/releases/
