### ISSUE TITLE
这个如何自行编译

### ISSUE THREAD

**Issue by shineme** [chushuai/wscan#29]
这个如何自行编译

PS C:\Program Files\Go\src\wscan> go build ./...
core\plugins\plugins.go:12:2: package wscan/core/plugins/crlf_injection is not in std (C:\Program Files\Go\src\wscan\core\plugins\crlf_injection)
package wscan/core
        imports wscan/core/entry
        imports wscan/core/ctrl
        imports wscan/core/plugins
        imports wscan/core/plugins/custom
        imports wscan/core/plugins/helper: no Go files in C:\Program Files\Go\src\wscan\core\plugins\helper
core\plugins\plugins.go:21:2: package wscan/core/plugins/redirect is not in std (C:\Program Files\Go\src\wscan\core\plugins\redirect)
package wscan/core
        imports wscan/core/entry
        imports wscan/core/ctrl
        imports wscan/core/plugins
        imports wscan/core/plugins/sql_injection: no Go files in C:\Program Files\Go\src\wscan\core\plugins\sql_injection
core\plugins\plugins.go:24:2: package wscan/core/plugins/ssrf is not in std (C:\Program Files\Go\src\wscan\core\plugins\ssrf)
core\output\htmlfile.go:27:12: pattern html_template.html: no matching files found
core\subdomain\datasource\alienvault.go:9:2: package wscan/core/fastdomain/geodb is not in std (C:\Program Files\Go\src\wscan\core\fastdomain\geodb)
core\subdomain\datasource\alienvault.go:10:2: package wscan/core/fastdomain/utils is not in std (C:\Program Files\Go\src\wscan\core\fastdomain\utils)
core\utils\guess\response.go:11:2: package wscan/core/apollo/http is not in std (C:\Program Files\Go\src\wscan\core\apollo\http)

提示缺少文件

**Comment by chushuai** [comment]
https://github.com/chushuai/wscan/issues/5

**Comment by chushuai** [comment]
已开源
https://github.com/chushuai/wscan/issues/50
