### ISSUE TITLE
误报率挺高

### ISSUE THREAD

**Issue by MAOGE555** [chushuai/wscan#6]
大佬，误报率好高呀，基本上我扫啥网站都能扫出来一堆SQL注入

**Comment by chushuai** [comment]
能否提供一下屏幕截图，或者发送一下扫描的目标?

**Comment by MAOGE555** [comment]
好的，可以的大佬。
![image](https://github.com/chushuai/wscan/assets/56222406/8f19e07d-84b4-4b65-9861-193f0f6b44a3)

**Comment by MAOGE555** [comment]
[结果.zip](https://github.com/chushuai/wscan/files/13837310/default.zip)

**Comment by chushuai** [comment]
@MAOGE555 感谢，涉及到隐私我先把报告删除了。

**Comment by MAOGE555** [comment]
好的^_^

**Comment by chushuai** [comment]
基于错误的SQL注入，我下个版本将会把True、False测试的快照都保存到结果中，以便于排查问题。

**Comment by MAOGE555** [comment]
nb，期待下个版本

**Comment by chushuai** [comment]
https://github.com/chushuai/wscan/releases/tag/1.0.13

**Comment by chushuai** [comment]
没有问题的话，先关闭这个issue
