### ISSUE TITLE
'doc/plugins/info_disclosure.py '这个python文件名的最后多了个空格

### ISSUE THREAD

**Issue by BenjaminS16** [chushuai/wscan#9]
error: invalid path 'doc/plugins/info_disclosure.py '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

'doc/plugins/info_disclosure.py '
这个python文件名的最后多了个空格，导致windows上clone不下来

**Comment by chushuai** [comment]
已修复https://github.com/chushuai/wscan/commit/e110bbe5f4d3d33f8deb0b763da8b0594ce5bc15

**Comment by BenjaminS16** [comment]
error: invalid path 'doc/plugins/sqli.py '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

'doc/plugins/sqli.py '这个文件有同样问题

另，建议在readme中添加自行编译的方法，谢谢

**Comment by chushuai** [comment]
Wscan目前仍在快速迭代中，具体时间表可参考社区的更新动态。待完全开源后，会提供详细的自行编译指南，敬请关注。
